resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.sample.app.configuration.App1,com.sample.app.configuration.App2
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info
